name: Build and push image to docker

on: push

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clona Repository
        uses: actions/checkout@v2
      - name: Builda Imagem
        id: build
        run: |
          docker build -t docker.pkg.gitub.com/${{github.repository}}/node-api-test:$(git log --format="%h" -n 1)
      - name: Imprimi coisa
        run: echo "${{ steps.build.outputs.version }}"
