name: Build and push image to docker

on: push

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clona Repository
        uses: actions/checkout@v2
      - name: Gera Id da Imagem
        id: generator
        run: echo '::set-output name=id::$(git log --format="%h" -n 1)'
      - name: Builda Imagem
        run: |
          docker build -t docker.pkg.gitub.com/${{github.repository}}/node-api-test:${{ steps.generator.outputs.id }}
      - name: Imprimi coisa
        run: echo "${{ steps.generator.outputs.id }}"
