name: Build and push image to docker

on: push

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clona Repository
        uses: actions/checkout@v2
      - name: Gera Id da Imagem
        id: generator
        run: echo '::set-output name=id::$(git log --format="%h" -n 1)'
      - name: Imprime id gerado
        run: echo "${{ steps.generator.outputs.id }}"
      - name: Realiza Build da Imagem
        run: |
          docker build -t docker.pkg.gitub.com/${{github.repository}}/node-api-test:${{ steps.generator.outputs.id }} .
      - name: Realiza push da Imagem
        run: docker push docker.pkg.gitub.com/${{github.repository}}/node-api-test:${{ steps.generator.outputs.id }}
